/**
 * Per-theme loudness normalisation. Every song is trimmed so that it plays at TARGET_LUFS
 * (integrated, ITU-R BS.1770, at the game's default volume settings) ± a small per-theme offset —
 * so walking from the beach into the mine or from a summer song into a winter one never jumps.
 *
 * MEASURED_LUFS is generated by `node scripts/audio-render.mjs --calibrate` (it renders each theme's
 * first 60 s through the real mixer and stores the level the song would have *without* this trim);
 * re-run it after changing an arrangement, instrument or mix.
 */
export const TARGET_LUFS = -21;

/** Deliberate offsets from the target (LU): the mine and the nights sit a little under the day. */
export const TARGET_OFFSET: Record<string, number> = {
  mine: -1, 'mine-ice': -1, 'mine-lava': -1,
  night: -0.8, 'night-spring': -0.8, 'night-fall': -0.8, 'night-winter': -0.8,
  rain: -0.5,
};

// @generated-begin (scripts/audio-render.mjs --calibrate)
export const MEASURED_LUFS: Record<string, number> = {
  'beach': -21.4,
  'fall': -18.5,
  'fall-2': -22.6,
  'fall-3': -23.3,
  'festival': -21.2,
  'festival-blossom': -22.4,
  'festival-harvest': -20.9,
  'festival-starfall': -22.5,
  'festival-tide': -19.8,
  'forest': -23.6,
  'inn': -22.3,
  'mine': -28.3,
  'mine-ice': -26.3,
  'mine-lava': -28.8,
  'night': -26,
  'night-fall': -21.7,
  'night-spring': -22.6,
  'night-winter': -21.8,
  'rain': -26.1,
  'spring': -21.5,
  'spring-2': -20.1,
  'spring-3': -20.4,
  'summer': -19.2,
  'summer-2': -22.3,
  'summer-3': -22.9,
  'title': -21.7,
  'town': -21.2,
  'winter': -20.3,
  'winter-2': -21.1,
  'winter-3': -20.6,
};
// @generated-end

/** Linear gain that brings theme `id` to its target (1 when it has not been measured yet). */
export function loudnessTrim(id: string): number {
  const m = MEASURED_LUFS[id];
  if (m === undefined || !Number.isFinite(m)) return 1;
  const target = TARGET_LUFS + (TARGET_OFFSET[id] ?? 0);
  return Math.max(0.2, Math.min(5, Math.pow(10, (target - m) / 20)));
}
